version: '3.8'

services:
  # Backend FastAPI Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiment-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    networks:
      - sentiment-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sentiment-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - sentiment-network
    restart: unless-stopped

networks:
  sentiment-network:
    driver: bridge

volumes:
  data:
  src:
